import pygame

ROOM_SIZE = 9
TILE_SIZE = 64
GAME_UI_WIDTH = 250
GAME_UI_BG = pygame.Color(75, 75, 75)
WINDOW_SIZE = (ROOM_SIZE * TILE_SIZE + GAME_UI_WIDTH, ROOM_SIZE * TILE_SIZE)
FRAMERATE = 60

ITEMSLOT_COUNT = 3
ITEMSLOT_SIZE = 48
ITEMSLOT_MARGIN_OUTER_LEFT = 16
ITEMSLOT_MARGIN_OUTER_RIGHT = 64
ITEMSLOT_MARGIN_INNER = (GAME_UI_WIDTH - ITEMSLOT_MARGIN_OUTER_LEFT - ITEMSLOT_MARGIN_OUTER_RIGHT - ITEMSLOT_SIZE * ITEMSLOT_COUNT) / (ITEMSLOT_COUNT - 1)
ITEMSLOT_MARGIN_LABEL = 4
ITEMSLOT_X = ROOM_SIZE * TILE_SIZE + ITEMSLOT_MARGIN_OUTER_LEFT
ITEMSLOT_Y = 175
ITEMSLOT_BG = pygame.Color(32, 32, 32)
ITEMSLOT_OUTLINE = pygame.Color(196, 196, 196)
ITEMSLOT_LABEL = pygame.Color(255, 255, 255)

BOMB_FUSE_LENGTH = FRAMERATE * 3
BOMBCOUNT_X = ITEMSLOT_X + ITEMSLOT_SIZE * 3 + ITEMSLOT_MARGIN_INNER * 3
BOMBCOUNT_Y = ITEMSLOT_Y + 8
BOMBCOUNT_MARGIN_LABEL = 12

GOLDAMOUNT_X = ROOM_SIZE * TILE_SIZE + 16
GOLDAMOUNT_Y = ITEMSLOT_Y + ITEMSLOT_SIZE + 24

MINIMAP_MARGIN = 16
MINIMAP_SIZE = GAME_UI_WIDTH - MINIMAP_MARGIN * 2
MINIMAP_X = ROOM_SIZE * TILE_SIZE + MINIMAP_MARGIN
MINIMAP_Y = WINDOW_SIZE[1] - MINIMAP_SIZE - MINIMAP_MARGIN
MINIMAP_BG = pygame.Color(0, 0, 0)
MINIMAP_OUTLINE = pygame.Color(196, 196, 196)
MINIMAP_ROOM_SIZE = 24

DEBUG = False
